
import { GoogleGenAI } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("AIzaSyBEbjkqHL4cGzrrlcv_mOZlufuVcTX9Km8");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export const generateThemedImage = async (
  base64ImageData: string,
  mimeType: string,
  prompt: string
): Promise<string> => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64ImageData,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64String = part.inlineData.data;
        const imageMimeType = part.inlineData.mimeType;
        return `data:${imageMimeType};base64,${base64String}`;
      }
    }
    
    throw new Error('No image was generated by the API.');
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    if (error.message.includes('API key not valid')) {
       throw new Error('The configured API key is invalid. Please check your configuration.');
    }
    throw new Error('Failed to generate image. The AI may have refused the request due to safety policies or other issues.');
  }
};
